filetype off

"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath^=~/.vim/bundle/repos/github.com/Shougo/dein.vim

" Required:
call dein#begin(expand('~/.vim/bundle'))

" Let dein manage dein
" Required:
call dein#add('Shougo/dein.vim', {'build': 'make'})

" Add or remove your plugins here:
call dein#add('Shougo/neosnippet.vim')
call dein#add('Shougo/neosnippet-snippets')

" You can specify revision/branch/tag.
" call dein#add('Shougo/vimshell', { 'rev': '3787e5' })
call dein#add('Shougo/vimshell')

call dein#add('Shougo/neocomplete.vim')
call dein#add('Shougo/unite.vim.git')
call dein#add('Shougo/vimproc.vim', {'build': 'make'})
call dein#add('tpope/vim-fugitive.git')
call dein#add('Yggdroot/indentLine')
call dein#add('majutsushi/tagbar')
call dein#add('thinca/vim-quickrun.git')
call dein#add('nvie/vim-flake8.git')
call dein#add('hynek/vim-python-pep8-indent')
call dein#add('pangloss/vim-javascript.git', {'lazy': 1, 'on_ft': ['javascript']})
call dein#add('scrooloose/syntastic')
call dein#add('mbbill/undotree')

call dein#config(['nvie/vim-flake8.git', 'hynek/vim-python-pep8-indent'], {
            \ 'lazy' : 1,
            \ 'on_ft' : ['python']
            \ })

" Required:
call dein#end()

" Required:
filetype plugin indent on

" If you want to install not installed plugins on startup.
"if dein#check_install()
"  call dein#install()
"endif

"End dein Scripts-------------------------


""" plugin settings
filetype plugin indent on

""" read settings
set runtimepath+=~/.vim
runtime! conf.d/*.vim

set tabpagemax=30
