filetype off

if has('vim_starting')
    set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))
set nocompatible

NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'https://github.com/vim-scripts/YankRing.vim.git'
NeoBundle 'https://github.com/tpope/vim-fugitive.git'
" NeoBundle 'https://github.com/Lokaltog/powerline.git'
NeoBundle 'https://github.com/tpope/vim-repeat.git'
NeoBundle 'https://github.com/Yggdroot/indentLine'
NeoBundle 'https://github.com/Shougo/unite.vim.git'
NeoBundle 'tpope/vim-surround'
NeoBundle 'scrooloose/syntastic'
NeoBundle 'Shougo/neocomplete.vim'
NeoBundle 'Shougo/neosnippet'
NeoBundle 'Shougo/neosnippet-snippets'
NeoBundle 'majutsushi/tagbar'
NeoBundle 'elixir-lang/vim-elixir'
NeoBundle 'thinca/vim-quickrun.git'
NeoBundle 'https://github.com/Shougo/vimproc.git', {
            \   'build' : {
            \       'linux' : 'make -f make_unix.mak',
            \   }
            \ }
NeoBundleLazy 'davidhalter/jedi-vim', {
            \ 'autoload' : {
            \   'filetypes' : ['python'],
            \   }
            \ }
NeoBundleLazy 'https://github.com/nvie/vim-flake8.git', {
            \ 'autoload' : {
            \   'filetypes' : ['python'],
            \   }
            \ }
NeoBundleLazy 'hynek/vim-python-pep8-indent', {
            \ 'autoload' : {
            \   'filetypes' : ['python'],
            \   }
            \ }
NeoBundleLazy 'https://github.com/pangloss/vim-javascript.git', {
            \ 'autoload' : {
            \   'filetypes' : ['javascript,html'],
            \   }
            \ }
NeoBundle 'marijnh/tern_for_vim', {
            \ 'build' : {
            \   'others' : 'npm install'
            \   }
            \ }
call neobundle#end()

""" plugin settings
filetype plugin indent on

""" read settings
set runtimepath+=~/.vim
runtime! conf.d/*.vim

set tabpagemax=30
