# .bashrc
shopt -s cdspell
shopt -s checkwinsize
shopt -s cmdhist
shopt -s dotglob
shopt -s expand_aliases
shopt -s extglob
shopt -s histappend
shopt -s hostcomplete
shopt -s nocaseglob

# alias setting
alias rm="rm -i"
alias grep="grep --color=auto"
alias ls="ls -GF"

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
export LANG=ja_JP.UTF-8

# history setting
export HISTSIZE=10000
export HISTFILESIZE=${HISTSIZE}
export HISTCONTROL=ignoreboth
export HISTIGNORE=ls:fg:exit
export PROMPT_COMMAND='history -a; history -r'

export PATH=/usr/local/bin:${PATH}:~/adt-bundle-linux-x86_64-20130219/sdk/tools

# Go path
export GOPATH=$HOME/go_work

# prompt
PS1='[\u@\h \W]\$ '
BROWSER=/usr/bin/xdg-open

# Source original environment variables
if [ -f ~/.bash_exports_origin ]; then
	. ~/.bash_exports_origin
fi

# virualenvwrapper
if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
    export WORKON_HOME=$HOME/.virtualenvs
    source /usr/local/bin/virtualenvwrapper.sh
fi
export PIP_RESPECT_VIRTUALENV=true

# bash completion
if [ -f /usr/local/etc/bash_completion ]; then
    . /usr/local/etc/bash_completion
fi

# git completation
if [ -f /usr/local/etc/bash_completion.d/git-prompt.sh ]; then
    source /usr/local/etc/bash_completion.d/git-prompt.sh
    if [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
        source /usr/local/etc/bash_completion.d/git-completion.bash
        GIT_PS1_SHOWDIRTYSTATE=true
        export PS1='\[\033[32m\]\u@\h\[\033[00m\]:\[\033[34m\]\w\[\033[31m\]$(__git_ps1)\[\033[00m\]\$ '
    fi
fi

# ssh 時に新規ウィンドウを作る
ssh_tmux() {
    ssh_cmd="ssh $@"
    tmux new-window -n "$*" "$ssh_cmd"
}

if [ $TERM = "screen" ] ; then
    tmux lsw
    if [ $? -eq 0 ] ; then
        alias ssh=ssh_tmux
    fi
fi
eval "$(direnv hook bash)"
